name: Build and Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:
env:
  ALGOLIA_PUSHKEY: ${{ secrets.ALGOLIA_PUSHKEY }}
  ALGOLIA_APP: ${{ secrets.ALGOLIA_APP }}
  ALGOLIA_QUERYKEY: ${{ secrets.ALGOLIA_QUERYKEY }}
  LATEST_GITHUB_KEY: ${{ secrets.LATEST_GITHUB_KEY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Get Resources
      uses: actions/checkout@v3
      with:
        repository: uiset-com/resources
        path: resources
    
    - name: Copy Assets To Public
      run: rsync -r --exclude '*/**/*.json' --exclude '.git' ./resources ./public/
    
    - name: Install npm
      run: npm install

    - name: Algolia Push
      run: npm run algolia:push
    
    - name: TestLog
      run: pwd && ls resources/color

    - name: Get Latest Resources
      run: npm run latest:resources
    
    - name: Generate
      run: npm run generate

    - name: Pushes to website repository
      id: push_directory
      uses: cpina/github-action-push-to-another-repository@main
      env:
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      with:
        source-directory: .output/public
        destination-github-username: 'uiset-com'
        destination-repository-name: 'uiset'
        user-email: 1246996371@qq.com
        commit-message: See ORIGIN_COMMIT from $GITHUB_REF
        target-branch: master

    